packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  core-js: false
  core-js-pure: false
  unrs-resolver: true

catalog:
  react: "^19.2.5"
  react-dom: "^19.2.5"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  typescript: "^6.0.3"
  eslint: "^9.39.4"
  prettier: "^3.8.3"
