name: AWS_CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # 환경변수 파일 생성
      - name: Generate .env.production
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_BASE_URL: ${{ secrets.TMDB_BASE_URL }}
          TMDB_IMAGE_BASE_URL: ${{ secrets.TMDB_IMAGE_BASE_URL }}
        run: |
          cat <<EOF > .env.production
          TMDB_API_KEY=$TMDB_API_KEY
          TMDB_BASE_URL=$TMDB_BASE_URL
          TMDB_IMAGE_BASE_URL=$TMDB_IMAGE_BASE_URL
          APP_PHASE=production
          EOF

      # 빌드
      - name: Build
        run: npm run build:production

      # 배포
      - name: S3 Deploy
        run: aws s3 sync ./dist s3://watcha-clone-prod-244892142287-ap-northeast-2-an/ --acl bucket-owner-full-control
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2

      # 기존 캐시 무효화
      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: '/index.html'
        continue-on-error: true
